name: remote-urban-tree-id
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - pytorch
  - torchvision
  - torchaudio
  - cpuonly
  - earthengine-api
  - python-dotenv
